### ISSUE TITLE
怎么用

### ISSUE THREAD

**Issue by liwuking** [weiofcn/smtp#1]
哥们 怎么用

**Comment by kenchowcn** [comment]
const unsigned char *filePath = "./test.jpg";
	const unsigned char *mailSubject = "for my love.";
	const unsigned char *mailBody = "I love you alice!!";

	const unsigned char *fromMailAddr= "ken@163.com";
	const unsigned char *mailPasswd= "ecila";
	const unsigned char *toMailAddr= "alice@163.com";
	const unsigned char *smtpUrl = "smtp.163.com";

替换上面的邮箱为你注册的邮箱地址、密码、服务器地址和邮件内容，filePath是附件的路径；你可能需要一点点SMTP协议的基础，然后，你会明白如何使用的。

希望能帮到你，谢谢！
